### PR TITLE
Complete database model for the Privacy Computation Engine

### PR DESCRIPTION
**Pull request by m4rk055**
Issue https://github.com/blindnet-io/product-management/issues/725

Added model containing all concerned objects and their relationships from the specification documents for the Privacy Computation Engine.
It is not a strict UML diagram.

### CODE REVIEW

**Comment by milstan** [comment]
You should mark this as ready for review, and assign Filip to merge it after reviews are in

**Comment by milstan** [comment]
If by "General Information" you understand all the information needed to respond to TRASNPARENCY requests at capture-time (GDPR Art. 13 & 14) then, you also need:
- Identity of the organization
- identity of the organization's legal representative
- in addition to DPO identity, DPO contact (which may be postal / e-mail adress or website URL)
- You also need general information about each knwon `selector` - about it's data category, the intended processing categories, the intended purposes, provenance, legal bases, and retention policies as the Data Subject can ask for those even beore providing any data. This is some sort of Intended Privacy Scope x Intended Retention Policy and Legal Base. General Configuration regarless of any data being known about the Data Subject.

See [Implications for Systems Implementing PRIV](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/RFC-PRIV.md#design-implications-for-systems-implementing-priv), and [Configuration chapter of Expected Behavior](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/expected-behavior.md#configuration-and-prerequisites)

**Review by milstan — CHANGES_REQUESTED** [review]
If by "General Information" you understand all the information needed to respond to TRASNPARENCY requests at capture-time (GDPR Art. 13 & 14) then, you also need:
- Identity of the organization
- identity of the organization's legal representative
- in addition to DPO identity, DPO contact (which may be postal / e-mail adress or website URL)
- You also need general information about each knwon `selector` - about it's data category, the intended processing categories, the intended purposes, provenance, legal bases, and retention policies as the Data Subject can ask for those even beore providing any data. This is some sort of Intended Privacy Scope x Intended Retention Policy and Legal Base. General Configuration regarless of any data being known about the Data Subject.

See [Implications for Systems Implementing PRIV](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/RFC-PRIV.md#design-implications-for-systems-implementing-priv), and [Configuration chapter of Expected Behavior](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/expected-behavior.md#configuration-and-prerequisites)

**Comment by noelmace** [comment]
@m4rk055 please make sure you addressed all feeback from @milstan and the model is up to date, then ask for a last review asap.

**Comment by m4rk055** [comment]
@milstan Model is updated.

> If by "General Information" you understand all the information needed to respond to TRASNPARENCY requests at capture-time (GDPR Art. 13 & 14) then, you also need:
> - Identity of the 
> - identity of the organization's legal 
> - in addition to DPO identity, DPO contact (which may be postal / e-mail adress or website URL)

Everything needed for `TRANSPARENCY` requests will be available in the database.

> You also need general information about each knwon selector - about it's data category, the intended processing categories, the intended purposes, provenance, legal bases, and retention policies as the Data Subject can ask for those even beore providing any data. This is some sort of Intended Privacy Scope x Intended Retention Policy and Legal Base. General Configuration regarless of any data being known about the Data Subject.

`Data Capture` and `Fragments` are removed and `selector` has the specified information.

**Review by milstan — APPROVED** [review]

**Comment by milstan** [comment]
Merging this as all requested changes have been adressed.

**Pull request merged**
