### PR TITLE
Update Sketches for Privacy Request Capture Interface

### PR DESCRIPTION
**Pull request by Clementinev**
Update the sketches for the following issues : 
- https://github.com/blindnet-io/privacy-components-web/issues/23
- https://github.com/blindnet-io/privacy-components-web/issues/20
- https://github.com/blindnet-io/privacy-components-web/issues/19

Here is the [Figma document link](https://www.figma.com/file/miUd9PEmLrjut53rwrQViX/Privacy-request-capture-service?node-id=0%3A1)

Close https://github.com/blindnet-io/product-management/issues/853
Close https://github.com/blindnet-io/product-management/issues/854
Close https://github.com/blindnet-io/product-management/issues/855

### CODE REVIEW

**Review by jboileau99 — APPROVED** [review]

**Comment by milstan** [comment]
So if we want to make `message` as difficult to find as possible then on the following screen:
image
We might want to make it available only after the user unfolds the acordeon of other demands. 

I would also suggest to visually distinghuish the answers in the final step. The user expects confirmation screen  and (suprisingly) there already the answers. It is very easiy to mistake them for some sort of confirmation and just close the window. I suggest making them stand out somehow visually, that the user knows those are the answers.

Also, for requests that are not automatically answerable, the workflow will be different. The user will be directed to a confirmation page (like on Privateform)
image
Some Requests will be partially answered right away, automatically, and partially later (after validation). We want the consistent user workflow. In fact we want the user alwyas to get confirmation. And there, on the same page, access reponses.

The progress bar should be optional. I can immagine clients not wanting it (especially that after the request is received, another progress bar appears for the status of the request).

**Review by milstan — CHANGES_REQUESTED** [review]
Several things:
- The interface MUST support multiple ways to authenticate the user (and [a priori](https://github.com/blindnet-io/product-management/blob/main/refs/schemas/priv/scenarios.md#a-priori-authentication) and [a posteriori](https://github.com/blindnet-io/product-management/blob/main/refs/schemas/priv/scenarios.md#a-posteriori-authentication)). Currently only authentication with ID document seems to be supported. We also need the whole thing to work with magic link (as it is probably easier to implement for september). - @jboileau99 your input would be valuable here.
Untitled 3
- In the MULTI-DEMAND situaiton, the combination of the progress bar and the demande choice panel appearing at the bottom of the page does not work. A user can, after hving made one demand, end-up in the second step ("chose type of demand" step finished and green circle full) yet they are offered the possibility to choose a demand (a second one). This simply does not work. It is confusing. 
- Target MUST NOT be considered a detail of a Demand, but of the whole Privacy Request. According to PRIV, `target` is a property of the Privacy Request, not of the Demand
Untitled
- The Date Range restriction is not to be considered a subcondition of IMAGE category. It can apply to other data as well. It is really a question how to allow it for thos who need it, but make it invisible for most. I would clrealy imagine "advanced settings" like in search, where the user can set more detailed criteria
Untitled.
- it is not possible to have "all of the above for targets" [larger targets include smaller ones.](https://github.com/blindnet-io/product-management/blob/main/refs/schemas/priv/RFC-PRIV.md#targets)
Untitled
- In Access demands, but also in general, I would put provenance under "advance settings"
- Create a password should not be mandatory even for access demand. If the user is logged in "a priori", it is not needed. Also whatever the apriori/aposteriori scenario if magic link is used, we can authenticate the user at the time of viewing the data. The password is only used when data is encrypted. It should be optional, and dependant on the authentication method.
- for REVOKE-CONSENT same as above for authentication (dependant on authentication method). However the user can REVOKE-CONSENT only when authenticated (apriori)

**Comment by milstan** [comment]
I still think the way multiple demands are handled is very complex and counter-intuitive with regards to the progress bar.
Here are two ideas I have:
1. At the screen where you can pick a demand, include a small, descrete textual link (or toggle button) - "select multiple". It should really be non prominent, and not distract the user from chosing the one they want (as most will only make one demand). When clicked the user has a possibility to click more then one demand (they are makred somehow as selected - they change color), and there is a "next button". Then the user provides details of demands one by one.
2. Remove the progress bar, at the end of details of a demand introduce a demand counter (like a basket - but different icon, showing the number of completed demands, initially 1). Ask the user if they want to add more, if so they are shown the same screen as at the beggining (they choose the type of demand) - all exactly the same (not when they scrol down - the previous demands are only visible in the counter/basket, and can be seen when clicked.

I let you discuss with @jboileau99 and find the easiest and more appropriate (or alternative to those two options).

Aslo @jboileau99 it should be possible to configure to receive (or not) the multi-demand requests. If false, the user can only make one demand per request, and must make another demand for another request. Some clients might want that.

@Clementinev I don't see the Provenance Restriction - it should be in advanced settings.

image
This does not seem the right progress bar for status page. Maybe the status page does not at all need a progress bar - but only an indication if all of the demands have received at least one response, or some more responses are still being expected. Its just a status. The progress bar here is not adapted, as also we never know when the process is finished. Maybe some answers will be made available later, maybe never.

image
This is difficult to produce. Each of the elements listed is a separate reponse to the same demand. When the demand is not a transparency demand, how would several responses look like? It should be consistent.

The status page needs a complete redo:
- There needs to be a clear indication that the Privacy Request has been received at a particular date.
- Statuses should clearly show (granted, partially granted, in review, denied)
- in the context of coordinated response scenario (but also in general as one system may provide several responses to the same demand) 1 demand - several responses.
- It needs to be clear what was demanded - and then what are the responses. There needs to be a place in the itnerface to show the different elements of demand in a user friendly way.

**Comment by jboileau99** [comment]
> Aslo @jboileau99 it should be possible to configure to receive (or not) the multi-demand requests. If false, the user can only make one demand per request, and must make another demand for another request. Some clients might want that.

Ok - we will have to decide what this means for transparency demands. Some background: With all the other action types it's a single one of these "demand builders" per demand, but for transparency we lump all the TRANSPARENCY.* actions into one demand builder, but in the background it's actually producing a demand per box the user checks. I think the current impression from the users perspective is that it's all one transparency demand though. 

I think if the component is configured to not allow multiple demands, users should still be able to select multiple boxes in the transparency form, even though this is technically multiple demands. Do you guys agree?

**Comment by milstan** [comment]
> > Aslo @jboileau99 it should be possible to configure to receive (or not) the multi-demand requests. If false, the user can only make one demand per request, and must make another demand for another request. Some clients might want that.
> 
> Ok - we will have to decide what this means for transparency demands. Some background: With all the other action types it's a single one of these "demand builders" per demand, but for transparency we lump all the TRANSPARENCY.* actions into one demand builder, but in the background it's actually producing a demand per box the user checks. I think the current impression from the users perspective is that it's all one transparency demand though.
> 
> I think if the component is configured to not allow multiple demands, users should still be able to select multiple boxes in the transparency form, even though this is technically multiple demands. Do you guys agree?

You are right @jboileau99 . I was imprecise. I meant to allow the clients to specify that at the demand type selections creen the selects one thing and then that's all - the user goes throught the workflow and is not offered to add any demands (in case of Transparency it means still several demands are produced, but in other cases non).

**Review by jboileau99 — APPROVED** [review]

**Comment by noelmace** [comment]
Given that @Clementinev and @milstan won't be available until September 1st and we are in a constant "work in progress" state, I'm merging this PR as is. The remaining requested changes should still be addressed in early September (see #892).

**Pull request merged**
