### PR TITLE
Define Diagrams and Sketches for local DELETE request

### PR DESCRIPTION
**Pull request by Clementinev**
This work is part of https://github.com/blindnet-io/product-management/issues/720

And is a subtask of https://github.com/blindnet-io/product-management/issues/803

**Goal**
Make Diagrams and Sketches for local DELETE request

Document : [Figma link to diagrams and sketches](https://www.figma.com/file/miUd9PEmLrjut53rwrQViX/Privacy-request-capture-service?node-id=649%3A106)

Close https://github.com/blindnet-io/product-management/issues/809

### CODE REVIEW

**Comment by Clementinev** [comment]
Updates [diagrams and sketches](https://www.figma.com/file/miUd9PEmLrjut53rwrQViX/Privacy-request-capture-service?node-id=0%3A1)

**Comment by Clementinev** [comment]
I updated sketches to resolve each points except the authentication ones :

>*The interface MUST support multiple ways to authenticate the user (and [a priori](https://github.com/blindnet-io/product-management/blob/main/refs/schemas/priv/scenarios.md#a-priori-authentication) and [a posteriori](https://github.com/blindnet-io/product-management/blob/main/refs/schemas/priv/scenarios.md#a-posteriori-authentication)). Currently only authentication with ID document seems to be supported. We also need the whole thing to work with magic link (as it is probably easier to implement for september). - @jboileau99 your input would be valuable here.

>*for REVOKE-CONSENT same as above for authentication (dependant on authentication method). However the user can REVOKE-CONSENT only when authenticated (apriori)

**Comment by milstan** [comment]
image
There is no  way to represent this in PRIV. A [Date Range](https://github.com/blindnet-io/product-management/blob/main/refs/schemas/priv/RFC-PRIV.md#date-range) Restriction only has from and to. No way to link it to a data category. When this restriction is set, it applies to the whole demand (and all data categories given in the Privacy Scope restriction of the demand)

**Comment by milstan** [comment]
I am asigning Noel to this, as I will be away

**Comment by Clementinev** [comment]
I've updated the date range section

**Review by milstan — DISMISSED** [review]

**Comment by milstan** [comment]
BTW @Clementinev I think the back button would be more intuitive at the bottom (where the "next" button is, and is the same form - maybe just fidderent color - more pale/gray)

**Comment by Clementinev** [comment]
Sketches updated : [link to figma sketches](https://www.figma.com/file/miUd9PEmLrjut53rwrQViX/Privacy-request-capture-service?node-id=649%3A106)

**Comment by noelmace** [comment]
Given that @Clementinev and @milstan won't be available until September 1st and we are in a constant "work in progress" state, I'm merging this PR as is.

**Pull request merged**
