### PR TITLE
Define Diagrams and Sketches for local ACCESS demand

### PR DESCRIPTION
**Pull request by Clementinev**
This work is part of https://github.com/blindnet-io/product-management/issues/720

And is a subtask of https://github.com/blindnet-io/product-management/issues/803

Goal
Make Diagrams and Sketches for local ACCESS demand

Document : [Figma link to diagrams and sketches](https://www.figma.com/file/miUd9PEmLrjut53rwrQViX/Privacy-request-capture-service?node-id=665%3A147)

Close https://github.com/blindnet-io/product-management/issues/804

### CODE REVIEW

**Review by milstan — CHANGES_REQUESTED** [review]
see the other pull request #856

**Comment by Clementinev** [comment]
I updated sketches to resolve each points except the authentication ones :

The interface MUST support multiple ways to authenticate the user (and [a priori](https://github.com/blindnet-io/product-management/blob/main/refs/schemas/priv/scenarios.md#a-priori-authentication) and [a posteriori](https://github.com/blindnet-io/product-management/blob/main/refs/schemas/priv/scenarios.md#a-posteriori-authentication)). Currently only authentication with ID document seems to be supported. We also need the whole thing to work with magic link (as it is probably easier to implement for september). - @jboileau99 your input would be valuable here.
for REVOKE-CONSENT same as above for authentication (dependant on authentication method). However the user can REVOKE-CONSENT only when authenticated (apriori)

**Comment by Clementinev** [comment]
Updated [diagrams and sketches](https://www.figma.com/file/miUd9PEmLrjut53rwrQViX/Privacy-request-capture-service?node-id=649%3A106)

**Comment by noelmace** [comment]
Given that @Clementinev and @milstan won't be available until September 1st and we are in a constant "work in progress" state, I'm merging this PR as is. The remaining requested changes should still be addressed in early September (see #892).

**Pull request merged**
