### PR TITLE
Add devkit data model

### PR DESCRIPTION
**Pull request by milstan**
Discuss devkit data model

### CODE REVIEW

**Comment by milstan** [comment]
Few comments:
- in PRIV, we separate [Target](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/RFC-PRIV.md#target-terms) from [Target Direction](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/RFC-PRIV.md#target-directions), as PRIV is language-independant and may be modeled and used in languages not supporting polymoriphism. However, according to the [Term Dot Notation](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/RFC-PRIV.md#term-dot-notation), Target Direction Terms are in fact subcategories of Target Terms. Since this data model is clealy a database model, it might be appropriate to consider Target Direction a subclass of Target.

- ["A demand with multiple restrictions MUST NOT have more than one restriction of the same type."](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/RFC-PRIV.md#demand-restrictions) according to PRIV. Maybe it is worth mentionning it here again, as under [Expected Behavior](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/expected-behavior.md) it is clearly advised that Systems reject Demands having muptile restrictions of the same type.

- Data Capture Fragment has both `selector` and `scope`. The value of `selector` property is a (subcategory of a) [Data Category Term](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/RFC-PRIV.md#data-categories). That in itself constitutes a Privacy Scope that is the value of `scope` proprety. This is redundant. PRIV suffers from the same issue (that, if solved here, should induce a change in PRIV). Maybe this redundance is OK, but it is worth considering changing this.

- Systems should be modeled. Their model should support [working with proveance](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/expected-behavior.md#working-with-provenance). There should probably be a Transfer object too.

- Legal Bases and Events should be modeled to support [Resolving Retention Policies](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/expected-behavior.md#resolving-retention-policies)

- [Privacy Scope Triples](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/expected-behavior.md#privacy-scope-triples) (and their mapping to legal bases in Eligible Privacy Scope) should be modeled to support [Privacy Algebra](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/expected-behavior.md#privacy-algebra)

- The model, as presented here, can't support Transparency requests. It should include configuration variables related to policies, locations etc. as specified [here](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/expected-behavior.md#configuration-and-prerequisites) and [here](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/RFC-PRIV.md#design-implications-for-systems-implementing-PRIV)

**Comment by milstan** [comment]
> > in PRIV, we separate [Target](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/RFC-PRIV.md#target-terms) from [Target Direction](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/RFC-PRIV.md#target-directions), as PRIV is language-independant and may be modeled and used in languages not supporting polymoriphism. However, according to the [Term Dot Notation](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/RFC-PRIV.md#term-dot-notation), Target Direction Terms are in fact subcategories of Target Terms. Since this data model is clealy a database model, it might be appropriate to consider Target Direction a subclass of Target.
> 
> Dot notation is already used in other types of terms, merging Target and Target direction is ok. We also remove duplication. Languages not supporting class polymorphism shouldn't be a concern, since they have other means of encoding it. We should only care about the PRIV language and make it as expressive as possible.

However the separation should remain in PRIV, IMHO, because certain `properties` only accept Tartget terms and not Target Direction Terms. It is in this model where we can take advantage of the subclass de factro introduced by the Term Dot Notation.

**Comment by filipblnt** [comment]
> Data Capture Fragment has both selector and scope. The value of selector property is a (subcategory of a) [Data Category Term](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/RFC-PRIV.md#data-categories). That in itself constitutes a Privacy Scope that is the value of scope proprety. This is redundant. PRIV suffers from the same issue (that, if solved here, should induce a change in PRIV). Maybe this redundance is OK, but it is worth considering changing this.

My understanding of `selector` is that, though a subcategory of DC, is something specific to client's system. Which makes it different from DC. For example, in system 1, we can have `selector=DEMOGRAPHIC.AGE.1246`, and within Privacy Scope the `Data Category=DEMOGRAPHIC.AGE`. If this understanding is correct, then we can't remove selector and rely only on Data Category from Privacy Scope because we loose information. I think this redundancy is ok here.

**Comment by milstan** [comment]
Regarding trasnfers, please note that when transfers happen across countries, additional things must be done to comply with [Chapter V of GDPR](https://gdpr-info.eu/chapter-5/). I intend to deal with this in [this issue](https://github.com/blindnet-io/product-management/issues/706).

**Comment by milstan** [comment]
@filipblnt for Consent, the author of consent can be a `parent` in the case the `data-subject` is a child, [according to GDPR](https://gdpr-info.eu/art-8-gdpr/).

**Comment by filipblnt** [comment]
W.r.t. [this comment](https://github.com/blindnet-io/product-management/pull/724#issuecomment-1166269873), how is it going to be modelled in PRIV?

**Comment by milstan** [comment]
@m4rk055 please review this (aim for compatibility with your own #730 ) and mark as aproved if OK.

**Comment by noelmace** [comment]
Up @m4rk055 for review ASAP.

**Review by m4rk055 — APPROVED** [review]

**Pull request merged**
